### ISSUE TITLE
Config error and argument exception

### ISSUE THREAD

**Issue by Ironjanowar** [Ironjanowar/breakfast_roulette#2]
There is a config error, very easy to fix.
<img width="530" alt="image" src="https://user-images.githubusercontent.com/9699815/65663403-fd0f3980-e036-11e9-8334-1cc329119402.png">

But then there is this error that you talked about @ignaciobll 
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/9699815/65663468-3051c880-e037-11e9-9814-b7ec9f366c36.png">

It would be nice to document a bit about this last error.

**Comment by ignaciobll** [comment]
Maybe this is because an instance of the database is not launched. I don't currently have a dev environment to test it, but Github Actions should have been triggered :whale:
